### ISSUE TITLE
Unable to generate meanjs using yeoman geneerator.

### ISSUE THREAD

**Issue by aladdam** [meanjs/generator-meanjs#117]
I have the below setup in my machine. Installed the generator generator-meanjs. But when I tried to install meanjs I am stuck with below error. Please suggest on what to do.

$ node --version
v4.0.0

$ npm --version
2.14.3

$ yo --version
1.4.8

When installed meanjs generator got the below warning. Succeded the installation though!.

$ npm install -g generator-meanjs
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-meanjs will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
generator-meanjs@0.1.12 c:\Program Files (x86)\nodejs\node_modules\generator-meanjs
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── underscore.inflections@0.2.1 (underscore@1.8.3, underscore.string@3.2.2)
└── yeoman-generator@0.17.7 (dargs@2.1.0, isbinaryfile@2.0.4, class-extend@0.1.1, diff@1.4.0, text-table@0.2.0, underscore.string@2.4.0, mime@1.3.4, async@0.9
.2, debug@1.0.4, grouped-queue@0.3.0, nopt@3.0.4, cross-spawn@0.2.9, run-async@0.1.0, shelljs@0.3.0, mkdirp@0.5.1, iconv-lite@0.4.11, glob@4.5.3, file-utils@0
.2.2, rimraf@2.4.3, findup-sync@0.1.3, github-username@1.1.1, download@1.0.7, lodash@2.4.2, request@2.61.0, cheerio@0.17.0, gruntfile-editor@0.2.0, inquirer@0
.7.3)
Also, $yo doctor doesn't complain anything.

And below is issue when I run $yo meanjs

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------'  |    Welcome to Yeoman,    |
    ( _'U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 '   `  |° ' Y `

You're using the official MEAN.JS generator.
? What would you like to call your application? meanstruct-test
? How would you describe your application? (Full-Stack JavaScript with MongoDB
? How would you describe your application? (Full-Stack JavaScript with MongoDB
? How would you describe your application? (Full-Stack JavaScript with MongoDB
? How would you describe your application? (Full-Stack JavaScript with MongoDB
? How would you describe your application? (Full-Stack JavaScript with MongoDB
? How would you describe your application? test
? How would you describe your application in comma seperated key words? (Mongo
? How would you describe your application in comma seperated key words? MongoD
 Express, AngularJS, Node.js
? What is your company/author name?
? Would you like to generate the article example CRUD module? Yes
? Which AngularJS modules would you like to include?
C:\Users\usr0001\AppData\Roaming\npm\node_modules\generator-meanjs\node_modul
\yeoman-generator\node_modules\isbinaryfile\index.js:21
                return cb(null, isBinaryCheck(bytes, size));
                       ^

TypeError: cb is not a function
    at C:\Users\usr0001\AppData\Roaming\npm\node_modules\generator-meanjs\nod
modules\yeoman-generator\node_modules\isbinaryfile\index.js:21:24
    at C:\Users\usr0001\AppData\Roaming\npm\node_modules\generator-meanjs\nod
modules\yeoman-generator\node_modules\download\node_modules\vinyl-fs\node_modu
s\graceful-fs\graceful-fs.js:42:10
    at C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\yeoman-envir
ment\node_modules\mem-fs\node_modules\vinyl-file\node_modules\graceful-fs\grac
ul-fs.js:42:10
    at C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\configstore\
de_modules\graceful-fs\graceful-fs.js:42:10

**Comment by codydaig** [comment]
The generator is not compatible with node version 4.0 yet.

**Comment by ilanbiala** [comment]
@codydaig @sarathmaddala the 0.4.1 generator was just published now. Try updating your npm package and then running it again. If it works, please close the issue.

**Comment by sarathmaddala** [comment]
@ilanbiala Thanks for looking into this. I tried with 0.4.1. Still issue exists. Below are details of test run.

C:\data\angularjs\test-gen>yo --version
1.4.8

C:\data\angularjs\test-gen>npm info generator-meanjs version
0.4.1

C:\data\angularjs\test-gen>npm info npm version
2.14.3



C:\data\angularjs\test-gen>yo meanjs

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------'  |    Welcome to Yeoman,    |
    ( _'U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 '   `  |° ' Y `

You're using the official MEAN.JS generator.
? What would you like to call your application? Abc
? How would you describe your application? (Full-Stack JavaScript with MongoDB,
? How would you describe your application? Full-Stack JavaScript with MongoDB, E
xpress, AngularJS, and Node.js
? How would you describe your application in comma seperated key words? (MongoDB
? How would you describe your application in comma seperated key words? MongoDB,
 Express, AngularJS, Node.js
? What is your company/author name?
? Would you like to generate the article example CRUD module? No
? Which AngularJS modules would you like to include? ngCookies, ngAnimate, ngTou
ch, ngSanitize
C:\Users\usr0001\AppData\Roaming\npm\node_modules\generator-meanjs\node_modules
\yeoman-generator\node_modules\isbinaryfile\index.js:21
                return cb(null, isBinaryCheck(bytes, size));
                       ^

TypeError: cb is not a function
    at C:\Users\usr0001\AppData\Roaming\npm\node_modules\generator-meanjs\node_
modules\yeoman-generator\node_modules\isbinaryfile\index.js:21:24
    at C:\Users\usr0001\AppData\Roaming\npm\node_modules\generator-meanjs\node_
modules\yeoman-generator\node_modules\download\node_modules\vinyl-fs\node_module
s\graceful-fs\graceful-fs.js:42:10
    at C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\yeoman-environ
ment\node_modules\mem-fs\node_modules\vinyl-file\node_modules\graceful-fs\gracef
ul-fs.js:42:10
    at C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\configstore\no
de_modules\graceful-fs\graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:82:15)

C:\data\angularjs\test-gen>

**Comment by codydaig** [comment]
@sarathmaddala This is not compatible with Node version 4.0.

**Comment by sarathmaddala** [comment]
Hi @codydaig , but @ilanbiala added 0.4.1. and asked to use it. Is it not made as fix for this issue on Node 4.0? If not, I will downgrade to 1.x Node version. please confirm.

**Comment by codydaig** [comment]
@sarathmaddala The node versions that we officially support are 0.10.x and 0.12.x. We never supported iojs. You'll have to use one of those versions for the app to work properly.

**Comment by sarathmaddala** [comment]
Thank you @codydaig. Will close the issue.

**Comment by ilanbiala** [comment]
@sarathmaddala what version of the generator are you using? It seems like it is pre 0.4.1, which is the latest on npm.

**Comment by codydaig** [comment]
@ilanbiala @sarathmaddala mentioned: 
```
$yo --version
1.4.8

$npm info generator-meanjs version
0.4.1

$npm info npm version
2.14.3

$node --version
v4.0.0

```

**Comment by ilanbiala** [comment]
When you do `yo meanjs`, I'm pretty sure it uses the globally installed generator. Also, @codydaig take a look at the prompts, he doesn't have the version selection one..

**Comment by codydaig** [comment]
Ah. Your right. I just looked at the version he logged in the console. 

@sarathmaddala You need to update your the global module for generator-meanjs.

**Comment by sarathmaddala** [comment]
Hey guys,

Thanks for keeping reopening it. I could move ahead with one more step but didn't finish successfully yet. It asked me to install Python and then vc++ express and still stuck with below error.

$ yo meanjs
undefined
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.1
0.4.1   
? In which folder would you like the project to be generated? This can be changed later. (mean) test4
? In which folder would you like the project to be generated? This can be changed later. (mean) test4
? In which folder would you like the project to be generated? This can be changed later. test4
Cloning the MEAN repo.......
? What would you like to call your application? test4
? How would you describe your application? (Full-Stack JavaScript with MongoDB, Express, AngularJS, a
? How would you describe your application? Full-Stack JavaScript with MongoDB, Express, AngularJS, an
d Node.js
? How would you describe your application in comma seperated key words? (MongoDB, Express, AngularJS,
? How would you describe your application in comma seperated key words? MongoDB, Express, AngularJS, 
Node.js
? What is your company/author name?
? Would you like to generate the article example CRUD module? Yes    
? Would you like to generate the chat example module? Yes    
   create test4\package.json
   create test4\bower.json
   create test4\config\env\default.js
Running npm install for you....
This may take a couple minutes.
Unhandled rejection Error: Command failed: C:\Windows\system32\cmd.exe /s /c "cd test4 && npm install
"
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.0.0","
npm":"3.3.3"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.0.0","npm":
"3.3.3"})
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global pangyp@2.3.2 should be installed with -g
npm WARN prefer global nodemon@1.3.8 should be installed with -g
npm WARN prefer global node-inspector@0.10.2 should be installed with -g
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_m
odules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\data\generators\test4\node_modules\bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm WARN install:bufferutil bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_m
odules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\data\generators\test4\node_modules\utf-8-validate
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm WARN install:utf-8-validate utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_m
odules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=c:\\da
ta\\generators\\test4\\node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v46-win32-ia32\\debug.node"
 "--module_name=debug" "--module_path=c:\\data\\generators\\test4\\node_modules\\v8-debug\\build\\deb
ug\\v0.4.6\\node-v46-win32-ia32"
gyp ERR! cwd c:\data\generators\test4\node_modules\v8-debug
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=c:\
data\generators\test4\node_modules\v8-debug\build\debug\v0.4.6\node-v46-win32-ia32\debug.node --modul
e_name=debug --module_path=c:\data\generators\test4\node_modules\v8-debug\build\debug\v0.4.6\node-v46
-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\data\generators\test4\node_modules\v8-deb
ug\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\data\\generators\\test4\\n
ode_modules\\v8-debug\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"

node-pre-gyp ERR! cwd c:\data\generators\test4\node_modules\v8-debug
node-pre-gyp ERR! node -v v4.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
npm WARN EPACKAGEJSON test4@0.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modu
les\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\data\generators\test4\npm-debug.log

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by mleanos** [comment]
@sarathmaddala To me it looks like some node modules are not compatible with Node v4. I'm also on Windows 7, but my Node version is 0.12.7

I'll look into this a bit more, but that's my initial guess.

**Comment by sarathmaddala** [comment]
@mleanos  Yes, it is creating the folder structure. Please see below screenshot.
![image](https://cloud.githubusercontent.com/assets/8279494/9925365/75bc6f2e-5cbf-11e5-99b8-b3257e1a01f5.png)

**Comment by zettai** [comment]
Hi everyone, I was having the same problem yesterday (windows 7 machine). I tried different versions of node 0.10.x and 0.12.x (64 bit) but generator 0.4.0 ... got different errors each time. I read this thread today and got it working using node 0.12.7 (32 bit) like this:
![capture](https://cloud.githubusercontent.com/assets/6027673/9937548/3c0182b8-5d2f-11e5-8524-cd1de70213a6.PNG)
Thanks for the help.

**Comment by aladdam** [comment]
Finally, I succeeded with some modifications.

After failing several times, I downgraded to Node 0.12.7 and below were the cofig I used.

Especially, i had to install node-gyp which needed python and VC++ Express. Followed instructions here https://github.com/nodejs/node-gyp .

Used meanjs 0.4.0.

C:\Users\usr0001>node -v
v0.12.7

C:\Users\usr0001>npm -v
2.11.3

C:\Users\usr0001>yo --version
1.4.8

C:\Users\usr0001>node-gyp -v
v3.0.3

C:\Users\usr0001>

Will setup all with Node 4.0 & new generator-meanjs version sometime later.

Thanks all.

**Comment by amaglonso** [comment]
I also got stopped at "Running npm install for you....This may take a couple minutes." I have the below versions:

node -v 
v0.12.7

npm -v
2.11.3

yo --version
1.5.0

node-gyp -v
v3.1.0

npm info npm version
3.4.0

**Comment by amccullough19** [comment]
also getting stuck at Running npm install for you... This may take a couple minutes

node -v 
v0.12.7

npm -v
2.11.3

yo --version
1.5.0

node-gyp -v
v3.1.0

npm info npm version
3.5.0

npm info generator-meanjs version
0.4.1

**Comment by kevinchevallier** [comment]
Hey guys, finally got it to work with this setup:
node: 0.12.8
npm: 2.14.9
yo: 1.5.0
node-gyp: not installed
npm info npm version: 3.5.0
npm info generator-meanjs version: 0.4.1

If it can help.

**Comment by hillkim7** [comment]
Thanks guys for mentioning version of npm packages.
It worked as it was written.

**Comment by vinayakvinay** [comment]
@codydaig hello Cody, What is the system requirements to use meanjs generator?

I can't succeed with Node v5.4.0 and npm v3.5.2. 

I read your notes about support to node and npm versions. Should I use older versions of node and npm or is there any chance to newer node versions?

**Comment by mscarchilli** [comment]
Same problem here.

OS: Win7
Node v5.5.0
npm v3.3.12
yo v1.8.4
generator-meanjs v0.4.4

```
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git clone --branch v0.4.2 https://github.com/meanjs/mean.git mean"
Cloning into 'mean'...
error: Couldn't set HEAD
fatal: Cannot update the ref 'HEAD'.
Unexpected end of command stream
```

**Comment by ilanbiala** [comment]
We don't support Node 5 currently.

**Comment by arunkasyakar11** [comment]
Getting the error while 
`$ yo meanjs`
my nodejs version : v7.5.0
npm : 4.1.2
yo version: 1.8.5

error log: 
Error: Command failed: cd . && npm install
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated mongodb@2.0.55: Please upgrade to 2.2.19 or higher
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated mongodb@2.0.49: Please upgrade to 2.2.19 or higher
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global node-gyp@3.5.0 should be installed with -g
npm WARN prefer global node-inspector@0.12.8 should be installed with -g
./Release/.deps/Release/obj.target/bufferutil/src/bufferutil.o.d.raw { dev: 2049,
  mode: 33204,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 19009650,
  size: 1318,
  blocks: 8,
  atime: 2017-02-20T11:18:25.000Z,
  mtime: 2017-02-20T11:18:25.000Z,
  ctime: 2017-02-20T11:18:25.285Z,
  birthtime: 2017-02-20T11:18:25.285Z }
./Release/.deps/Release/obj.target/validation/src/validation.o.d.raw { dev: 2049,
  mode: 33204,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 19009685,
  size: 1426,
  blocks: 8,
  atime: 2017-02-20T11:18:28.000Z,
  mtime: 2017-02-20T11:18:28.000Z,
  ctime: 2017-02-20T11:18:28.757Z,
  birthtime: 2017-02-20T11:18:28.757Z }
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.5.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::Call(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:38:27: error: no matching function for call to ‘v8::Debug::Call(v8::Local<v8::Function>&)’
         v8::Debug::Call(fn);
                           ^
In file included from ../src/debug.cc:1:0:
/home/arun/.node-gyp/7.5.0/include/node/v8-debug.h:198:28: note: candidate: static v8::MaybeLocal<v8::Value> v8::Debug::Call(v8::Local<v8::Context>, v8::Local<v8::Function>, v8::Local<v8::Value>)
   static MaybeLocal<Value> Call(Local<Context> context,
                            ^
/home/arun/.node-gyp/7.5.0/include/node/v8-debug.h:198:28: note:   candidate expects 3 arguments, 1 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::SendCommand(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:46:61: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                                             ^
In file included from ../src/debug.cc:1:0:
/home/arun/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/arun/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::RunScript(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:61:67: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Local<Context> debug_context = v8::Debug::GetDebugContext();
                                                                   ^
In file included from ../src/debug.cc:1:0:
/home/arun/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/arun/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc:66:54: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
           debug_context = v8::Debug::GetDebugContext();
                                                      ^
In file included from ../src/debug.cc:1:0:
/home/arun/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/arun/.node-gyp/7.5.0/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/arun/nodeExamples/meanblog/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/usr/bin/nodejs" "/home/arun/nodeExamples/meanblog/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/arun/nodeExamples/meanblog/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/arun/nodeExamples/meanblog/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /home/arun/nodeExamples/meanblog/node_modules/v8-debug
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/arun/nodeExamples/meanblog/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/arun/nodeExamples/meanblog/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/arun/nodeExamples/meanblog/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/arun/nodeExamples/meanblog/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-62-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/arun/nodeExamples/meanblog/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/arun/nodeExamples/meanblog/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm WARN mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/arun/nodeExamples/meanblog/npm-debug.log

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
