### ISSUE TITLE
Generation fails on Windows: 'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by MonProspecteur** [meanjs/generator-meanjs#121]
Maybe we could use https://github.com/isaacs/rimraf to also support Windows ?

Any other suggestions?

**Comment by ilanbiala** [comment]
@MonProspecteur people have suggested using Git Bash. I'll look into better support.

**Comment by rlyman40** [comment]
I am somewhat new to all this so please take this with a large grain of salt. Instead of adding another dependency on another package could we not just use what is already available.

in index.js

var rmcmd = 'rm ';
var rmrfcmd = 'rm -rf ';
if (process.platform === 'win32') {
  rmrfcmd = 'rmdir /s /q ';
  rmcmd = 'del ';
}

then use path.join to generate the correct paths for the remove commands.

This may not be the best way to do it but it is working on my Windows VM.

**Comment by codydaig** [comment]
@rlyman40 Thanks for that! I actually should have used the built in filesystem module in node to handle this for us. I have an open PR that will resolve part of this issue, and I will get the rest of the issue worked out in another PR later today.

**Comment by narendranss** [comment]
@ilanbiala Git Bash work around works only if we are using only one version of node.jsf from the begining. I had node.js 0.10.36 version, I update to 0.12.7 in cmd. Git Bash did not recognize the udpate to newer version and was still working in 0.10.36.

**Comment by mthomson19** [comment]
Cloning the MEAN repo.......
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "rm ./mean/bower.json"
'rm' is not recognized as an internal or external command,
operable program or batch file.

I am having the same problem. I am new to the MEAN stack and application generation. Does anyone have a suggestion to resolve this issue? I am developing on a Windows7 machine. Should I use a Linux machine?

**Comment by rlyman40** [comment]
Marc,
I believe that Cody is working on a more generic solution but as a
workaround I did this (knowing that this is probably not the best way to
solve this).

in your C:\Users\{your user
name}\AppData\Roaming\npm\node_modules\generator-meanjs\app\index.js

add this near the top ( I added it just below the exec function around line
20)

var rmcmd = 'rm ';
var rmrfcmd = 'rm -rf ';
if (process.platform === 'win32') {
rmrfcmd = 'rmdir /s /q ';
rmcmd = 'del ';
}

then use path.join to generate the correct paths for the remove commands.

in the removeFiles function I changed the push to

remove.push(exec(rmcmd + path.join('.', folder, files[i])));

then in the removeChatExample and I changed the exec to

exec(rmrfcmd + path.join(folderPath, 'modules/chat'))

and in the removeArticlesExample function

exec(rmrfcmd + path.join(folderPath, 'modules/articles'))

On Thu, Nov 19, 2015 at 6:28 AM, Marc Steven Thomson <
notifications@github.com> wrote:

> Cloning the MEAN repo.......
> Error: Command failed: C:\Windows\system32\cmd.exe /s /c "rm
> ./mean/bower.json"
> 'rm' is not recognized as an internal or external command,
> operable program or batch file.
>
> I am having the same problem. I am new to the MEAN stack and application
> generation. Does anyone have a suggestion to resolve this issue? I am
> developing on a Windows7 machine. Should I use a Linux machine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/generator-meanjs/issues/121#issuecomment-158029498>
> .
>



-- 

Ralph Lyman

Software Engineer

(585)506-4837

Fujifilm North America Corporation

Fujifilm Systems and Software Development

1565 Jefferson Road

Building 300, Suite 320

Rochester, NY 14623

-- 
NOTICE: This message, including any attachments, is only for the use of the 
intended recipient(s) and may contain confidential and privileged 
information, or information otherwise protected from disclosure by law.  If 
the reader of this message is not the intended recipient, you are hereby 
notified that any use, disclosure, copying, dissemination or distribution 
of this message or any of its attachments is strictly prohibited.  If you 
received this message in error, please contact the sender immediately by 
reply email and destroy this message, including all attachments, and any 
copies thereof.

**Comment by vvint3r** [comment]
This is solved by using "Git Bash Here" on the project folder. Then yo meanjs worked perfectly!

**Comment by ilanbiala** [comment]
@codydaig and I have worked to get rid of many of the bugs in 0.4.1, and today we released 0.4.2. Please try it out and if it resolves your issues, let us know!

**Comment by atomicnation** [comment]
Yep, no problems using Git Shell!!!
Thanks to all.

**Comment by ilanbiala** [comment]
@codydaig we forgot to switch the remove functionality to something other than `rm`. Should we use rimraf as someone suggested?

**Comment by codydaig** [comment]
@ilanbiala Crap. Yes. That's what I would recommend. Do you want to submit the PR or do you want me to? I'm moving this week, so I probably won't be able to submit one until the weekend.

**Comment by ilanbiala** [comment]
I have finals until next week, so I'll also be busy for the next week. If you can get to it first, awesome. If not, then after the 17th I'll probably do it.

**Comment by mukeshmk** [comment]
Hi, I need some help here.
I am running a Win 10 PC, I have installed MEAN Stack. and when I run the "yo meanjs" command in the terminal, I am getting the following error msg:

![capture](https://cloud.githubusercontent.com/assets/7903100/12429776/2ceffe68-bf12-11e5-9daa-b766b6f2844e.PNG)

I have even tried using the "Git Bash" here option suggested here, it didn't work for me, but the above error didn't pop up but still the "install" part kept going for over 2 hours. (Which I then had to cancelled cause I had other work)

Note:
-I have installed python 2.7.7, Microsoft Visual C++ and Node.js
-I have also followed these command in admin mode in my cmd.
--npm install -g bower
--npm install -g grunt-cli
--npm install -g yo
--npm install -g generator-meanjs

Please help me out.
Thank You :)

**Comment by ilanbiala** [comment]
0.4.3 has been published, please try to see if the new version fixes your issue.

**Comment by codydaig** [comment]
@MonProspecteur Feel free to reopen this issue if the latest version does not fix the issue. Thanks!
