### ISSUE TITLE
Upgrade path?

### ISSUE THREAD

**Issue by ignasg** [meanjs/generator-meanjs#147]
Hi All,  
I have used meanjs version 0.3.x with generator to scaffold the initial application as 0.4 was unstable at that time. We are considering the upgrade to meanjs 0.4.x to be able to use new mongoose, etc. However I am not able to find any information for upgrade path when using the generator. Does it mean I have to rebuild the application more or less from scratch? 
Also is the generator working well for 0.4.x ?

**Comment by ilanbiala** [comment]
@codydaig and I have worked to get rid of many of the bugs in 0.4.1, and today we released 0.4.2. It should not have the bugs that came with 0.4.1, and it should allow you to scaffold 0.4.2 apps as well. Unfortunately, the upgrade path isn't smooth because there were lots of changes in the framework itself. If you have any specific questions, please feel free to ask.
