### ISSUE TITLE
Is there anyway to make space instead of tab in the generation files?

### ISSUE THREAD

**Issue by xiaoquqi** [meanjs/generator-meanjs#68]
I found all the generate files use tab as default, is there any configuration to limit to use spaces instead? Or I should do sed after I generate the files?

Thanks.

**Comment by 0x24a537r9** [comment]
Tabs vs. spaces is always a contentious issue, so I won't argue that either is intrinsically better, but I tend to agree that it should be an option since sed-ing is prone to be forgotten and the link the .editorconfig file references for its JS style (https://github.com/felixge/node-style-guide#2-spaces-for-indention) actually specifically recommends using 2 spaces for indentation (meaning the .editorconfig is in fact internally inconsistent).

Given that both node.js itself and consequently a majority of node.js and Express code uses 2-space indentation as a standard, I would argue that 2-space indentation should be the default for no other reason than simple consistency. Lacking that (perhaps reasonably to maintain the unfortunate inconsistency of the core meanjs codebase), I would at least hope for a means of configuring the meanjs generators to perform the sed automatically.

To clarify the specific needs, what would such a PR entail? I'm unfamiliar with the innards of Yeoman, and thus unaware whether the kind of generator-module-level configuration needed to record whether to use tabs/spaces in future yo's is even supported.

**Comment by lirantal** [comment]
Hey guys,

We have indeed pushed this change in and on the upcoming 0.4.0 release of MEAN.JS we will be using 2 spaces. As of now, we re not planning to release any updates to the generator repository (sorry).

It's coming.. really really soon, as in this week! Stay tuned.

**Comment by xiaoquqi** [comment]
Sound great to me. Thanks.

**Comment by 0x24a537r9** [comment]
Woohoo! One more reason to love MEAN.JS.

**Comment by lirantal** [comment]
@xiaoquqi @0x24a537r9 - 0.4.0 released now and merged into master branch.
You can also find the 0.4.0 tag here: https://github.com/meanjs/mean/releases/tag/v0.4.0
